
[global]
# source of logs, could be 'stdin' or 'journal'
log_source = "stdin"

# local UDP-port to send from
sender_port = 1234

[watched]
# Parameters in this section are observed by the utility
# and could be modified on the fly

# (optional) team
#team = "cool-team"

# (optional) service
service = "the-most-important-one"

# Graylog address to send to
graylog_addr = "127.0.0.1:1235"

# none/gzip/zlib
compression = "none"

# System logging level threshold
# +----------------+------------------+
# | possible value | Systemd priority |
# +----------------+------------------+
# |    emergency   |       0          |
# |      alert     |       1          |
# |     critical   |       2          |
# |      error     |       3          |
# |     warning    |       4          |
# |     notice     |       5          |
# |  informational |       6          |
# |     debug      |      >= 7        |
# +----------------+------------------+
log_level_system = "warning"

# (optional) filter by logging level in message
# allowed levels: fatal/panic/error/warning/info/debug
#log_level_message = "info"
